name: CI

# Define the events that trigger the workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs to be run
jobs:
  build:
    # Specify the type of runner to use
    runs-on: ubuntu-latest

    # Define the steps to be executed
    steps:
    # Step 1: Check out the repository
    - uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
        echo "Dependencies installed."

    # Step 4: Run tests
    - name: Run tests
      run: |
        echo "Running tests..."
        npm test
        echo "Tests completed."

    # Step 5: Build the project
    - name: Build
      run: |
        echo "Building project..."
        npm run build
        echo "Build successful."
        echo "Deploying to production..."
        # Add your deployment command here
        # e.g., npm run deploy
        echo "Deployment successful."